namespace WebAPI.Extentions
{
    public static class StringExtensions
    {
       // public static string ToCamelCase(this string value) {  return value.ToLower(); }  //autogenerated
       public static bool IsEmpty(this string value) {  return string.IsNullOrEmpty(value.Trim()); }
    }
}
